spring:
  profiles:
    active: -dev
---
server:
  port: 8002
spring:
  application:
    name: PRODUCT-SERVICE
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jd
    username: root
    password: luomeng
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
mybatis-plus:
  mapper-locations: classpath:cn/luomengde/jd/mapper/*Mapper.xml
  type-aliases-package: cn.luomengde.jd.domain,cn.luomengde.jd.query
---
server:
  port: 8003
spring:
  application:
    name: PRODUCT-SERVICE-TEST
  profiles: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jd_test
    username: root
    password: luomeng
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
mybatis-plus:
  mapper-locations: classpath:cn/luomengde/jd/mapper/*Mapper.xml
  type-aliases-package: cn.luomengde.jd.domain,cn.luomengde.jd.query